vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<leader>]", ":lnext <Cr>")
vim.keymap.set("n", "<leader>[", ":lprev <Cr>")
vim.keymap.set("n", "]q", ":cnext <Cr>")
vim.keymap.set("n", "[q", ":cprev <Cr>")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-h>", "<C-w>h")

require("keymaps.file_copy").setup()
