return {
	"slugbyte/lackluster.nvim",
	lazy = false,
	priority = 1000,
	config = function()
		local color = require("lackluster.color")
		require("lackluster").setup({
			disable_plugin = {},
			tweak_background = {
				normal = "none",
				popup = "none",
				telescope = "none",
			},
			tweak_highlight = {
				Cursor = { reverse = true },
				CursorLineNr = { fg = color.gray9, bold = true },
				Delimiter = { fg = color.lack },
				DiagnosticHint = { fg = color.green },
				DiagnosticInfo = { fg = color.blue },
				DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
				DiagnosticWarn = { fg = color.orange },
				Normal = { fg = color.gray8 },
				OilDir = { fg = color.blue },
				TelescopeMatching = { fg = color.orange, bold = true, italic = false },
				TelescopeSelection = { fg = color.gray8, bg = color.gray3 },
				TelescopeSelectionCaret = { fg = color.orange, bold = true, italic = false },
				["@boolean"] = { fg = color.lack },
				["@character"] = { link = "@string" },
				["@comment"] = { fg = color.gray5 },
				["@constant.builtin"] = { fg = color.lack },
				["@constructor"] = { link = "Delimiter" },
				["@function.builtin"] = { fg = color.gray5 },
				["@function.call"] = { fg = color.gray8 },
				["@function.method"] = { fg = color.gray8 },
				["@function.method.call"] = { fg = color.gray8 },
				["@keyword"] = { fg = color.gray6, bold = true },
				["@keyword.return"] = { link = "@keyword" },
				["@lsp"] = { fg = color.gray8 },
				["@number"] = { fg = color.blue },
				["@number.float"] = { link = "@number" },
				["@operator"] = { fg = color.gray6, bold = true },
				["@property"] = { fg = color.lack },
				["@punctuation.bracket"] = { link = "Delimiter" },
				["@string"] = { fg = color.blue },
				["@string.regexp"] = { link = "@string" },
				["@type"] = { fg = color.gray9 },
				["@variable"] = { fg = color.gray7 },
			},
		})
		vim.cmd.colorscheme("lackluster")
	end,
}
